In [9]:
#Section A:
#1.Various operations on list
List=[10,20,10,30,40]
print(List)
List.append(50)
print(List)
List.extend([60])
print(List)
List.insert(3,20)
print(List)
List.remove(10)
print(List)
List.pop()
print(List)
List.pop(2)
print(List)
print(List.index(30))
print(List.count(10))
List.sort()
print(List)
List.reverse()
print(List)
List.clear()
print(List)

[10, 20, 10, 30, 40]
[10, 20, 10, 30, 40, 50]
[10, 20, 10, 30, 40, 50, 60]
[10, 20, 10, 20, 30, 40, 50, 60]
[20, 10, 20, 30, 40, 50, 60]
[20, 10, 20, 30, 40, 50]
[20, 10, 30, 40, 50]
2
1
[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]
[]


In [50]:
#2.Tuple 
Tuple=("Rithik","Roshan","Sahani")
print(Tuple)
Tuple[1]="Kohli"
#Ans:Tuple is a data structure, where it  does not support/allow to change the elements after they are assigned.
#These tuples are immutable and cannot be modified or altered after assigning elements.

('Rithik', 'Roshan', 'Sahani')


TypeError: 'tuple' object does not support item assignment

In [53]:
#3.Set
Set={1,2,3,4,2,1,5}
print(Set)
#A set is a unordered collection of data. where it does not aloow any duplicate values in set, which means values should be unique. 
#The set is mutable but allows no duplication of elements and unordered. 

{1, 2, 3, 4, 5}


In [66]:
#4.Dictionary
Dict={"Name":"Rithik",
      "Age":21,
      "city":"Hyderabad"}
Dict["Age"]=22
Dict["email"]="rithikroshan@gmail.com"
print(Dict)

{'Name': 'Rithik', 'Age': 22, 'city': 'Hyderabad', 'email': 'rithikroshan@gmail.com'}


In [69]:
#5.Eligibile for vote
age=int(input("Enter the age:"))
if (age >= 18):
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter the age: 18


Eligible to vote


In [94]:
#6.Grading mechanism
Marks=int(input("Enter the marks :"))
if Marks >= 90:
    print("A Grade")
elif Marks >= 75:
    print("B Grade")
elif Marks >= 50:
    print("C Grade")
else:
    print("Fail")

Enter the marks : 92


A Grade


In [106]:
#7.Program on Numbers
num=int(input("Enter a number:"))
if num > 1:
    if num % 2 == 0:
        print("It is a positive and Even Number")
    else:
        print("Not an even number")
elif num == 0:
    print("It is zero")
else:
    print("It is a Negative number")

Enter a number: 22


It is a positive and Even Number


In [5]:
#Section B
#8.Numpy arrays
import numpy as np
A=np.array(5)
print(A)
B=np.array([1,2,3,4,5])
print(B)
C=np.array([[10,20,30],
            [40,50,60]])
print(C)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [6]:
#9.Numpy Random
A=np.random.randint(1,101,(4,4))
print(A)    

[[63 41 65 74]
 [55 37 76 41]
 [32 41 82 73]
 [67 31 44 51]]


In [7]:
#10.Numpy to pandas conversion
import pandas as pd
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
df=pd.DataFrame(A,columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [25]:
#Section C
#11.Exploring pandas
Data={"Names":["Rithik","Rithik","Sahani","Dhanunjay","Sandy","praveen","abhi","ankith","vamshi","sanju"],
      "Age":[21,21,19,22,23,18,17,16,15,14],
      "City":["kataram","kataram","uppal","madhapur","nagole","karimnagar","jubliee","banjara","delhi","pune"],
      "Salary":[6000,6000,3000,np.nan,4000,np.nan,5000,6000,7000,np.nan]}
df=pd.DataFrame(Data)
df

,Names,Age,City,Salary
0,Rithik,21,kataram,6000.0
1,Rithik,21,kataram,6000.0
2,Sahani,19,uppal,3000.0
3,Dhanunjay,22,madhapur,NaN
4,Sandy,23,nagole,4000.0
5,praveen,18,karimnagar,NaN
6,abhi,17,jubliee,5000.0
7,ankith,16,banjara,6000.0
8,vamshi,15,delhi,7000.0
9,sanju,14,pune,NaN


In [26]:
print(df[['Names','City']])

       Names        City
0     Rithik     kataram
1     Rithik     kataram
2     Sahani       uppal
3  Dhanunjay    madhapur
4      Sandy      nagole
5    praveen  karimnagar
6       abhi     jubliee
7     ankith     banjara
8     vamshi       delhi
9      sanju        pune


In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Names   10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [28]:
df.describe()

,Age,Salary
count,10.000000,7.000000
mean,18.600000,5285.714286
std,3.098387,1380.131119
min,14.000000,3000.000000
25%,16.250000,4500.000000
50%,18.500000,6000.000000
75%,21.000000,6000.000000
max,23.000000,7000.000000


In [29]:
df=df.drop('City',axis=1)
df

,Names,Age,Salary
0,Rithik,21,6000.0
1,Rithik,21,6000.0
2,Sahani,19,3000.0
3,Dhanunjay,22,NaN
4,Sandy,23,4000.0
5,praveen,18,NaN
6,abhi,17,5000.0
7,ankith,16,6000.0
8,vamshi,15,7000.0
9,sanju,14,NaN


In [36]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df

,Names,Age,Salary
0,Rithik,21,6000.000000
2,Sahani,19,3000.000000
3,Dhanunjay,22,5285.714286
4,Sandy,23,4000.000000
5,praveen,18,5285.714286
6,abhi,17,5000.000000
7,ankith,16,6000.000000
8,vamshi,15,7000.000000
9,sanju,14,5285.714286


In [34]:
df=df.drop_duplicates()
df

,Names,Age,Salary
0,Rithik,21,6000.000000
2,Sahani,19,3000.000000
3,Dhanunjay,22,5285.714286
4,Sandy,23,4000.000000
5,praveen,18,5285.714286
6,abhi,17,5000.000000
7,ankith,16,6000.000000
8,vamshi,15,7000.000000
9,sanju,14,5285.714286
